mysiteshow/musicapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'musicapp'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r"^(?P<album_id>[0-9]+)/favorite/$", views.favorite, name="favorite"),
    url(r'album/add/$',views.AlbumCreate.as_view(), name='album-add')
]

mysiteshow/mysiteshow/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'music/',include('musicapp.urls'))
]

mysiteshow/musicapp/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    album_title =  models.CharField(max_length= 500)
    artist = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('musicapp:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title =  models.CharField(max_length=200)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album.artist + '-' + self.song_title

mysiteshow/musicapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
from django.views.generic.edit import CreateView
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'musicapp/index.html'
    context_object_name = 'albums'
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'musicapp/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk = request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, 'musicapp/detail.html', {
            'album' : album,
            'error_message' : "You did not select a valid song",
        })
    else:
        if selected_song.is_favorite == True:
            selected_song.is_favorite = False
            selected_song.save()
        else:
            selected_song.is_favorite = True
            selected_song.save()

        return render(request,'musicapp/detail.html', {'album': album})

        # Create your views here.

mysiteshow/musicapp/templates/musicapp/album_form.html
{% extends 'musicapp/base.html' %}
{% block addactive %}active{% endblock %}

{% block title %} Add a New Album {% endblock %}
{% block body %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
     {% csrf_token %}
    {% include 'musicapp/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
    </form>
{% endblock %}

mysiteshow/musicapp/templates/musicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'musicapp/style2.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <script src = "http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="{%  url "musicapp:index"%} ">Minju</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class = "{% block albumactive %}{% endblock %}"><a href="{%  url "musicapp:index"%}"><span class = "glyphicon glyphicon-cd"></span>&nbsp; Albums <span class="sr-only">(current)</span></a></li>
        <li class="{% block songactive %}{% endblock %}"><a href="#"><span class = "glyphicon glyphicon-music"></span>&nbsp; Songs</a></li>

      </ul>


      <ul class="nav navbar-nav navbar-right">
        <li class="{% block addactive%}{% endblock %}"><a href="{% url 'musicapp:album-add'%}">
            <span class = "glyphicon glyphicon-plus"></span>&nbsp;Add Albums</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Login</a></li>
            <li class="divider"></li>
            <li><a href="#">My Page</a></li>
          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block body %}
{% endblock %}
</body>
</html>

mysiteshow/musicapp/templates/musicapp/detail.html
{%  extends 'musicapp/base.html' %}

{% block title %}
Songs
{% endblock %}


{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'musicapp:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'musicapp:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="#">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

{% block songactive %}
    active
{% endblock %}

mysiteshow/musicapp/templates/musicapp/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-2">{{ field }}</div>
    </div>

{% endfor %}

mysiteshow/musicapp/templates/musicapp/index.html
{%  extends 'musicapp/base.html' %}

{% block title %}
All albums
{% endblock %}


{% block body %}
   <div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'musicapp:detail' album.id %}">
                            <img src="{{ album.album_logo }}" width="500" height="500" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h5>{{ album.album_title }}</h5>
                            <h6>{{ album.artist }}</h6>

                            <!-- View Details -->
                            <a href="{% url 'musicapp:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="#" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
               {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock %}
{% block albumactive %}
    active
{% endblock %}